config/routes.rb
Rails.application.routes.draw do
  resources :monsters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: %i[ show edit update destroy ]

  # GET /monsters or /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1 or /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters or /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to monster_url(@monster), notice: "Monster was successfully created." }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1 or /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to monster_url(@monster), notice: "Monster was successfully updated." }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1 or /monsters/1.json
  def destroy
    @monster.destroy

    respond_to do |format|
      format.html { redirect_to monsters_url, notice: "Monster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monster_params
      params.require(:monster).permit(:name, :hp, :mp, :is_undead, :desc, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_with(model: monster, class: "contents") do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
        <% monster.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :hp %>
    <%= form.number_field :hp, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :mp %>
    <%= form.number_field :mp, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :is_undead %>
    <%= form.check_box :is_undead, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :desc %>
    <%= form.text_area :desc, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/monsters/_monster.html.erb
<div id="<%= dom_id monster %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= monster.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Hp:</strong>
    <%= monster.hp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Mp:</strong>
    <%= monster.mp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Is undead:</strong>
    <%= monster.is_undead %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Desc:</strong>
    <%= monster.desc %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Avatar:</strong>
		<%= image_tag monster.avatar %>
    <%= link_to monster.avatar.filename, monster.avatar if monster.avatar.attached? %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this monster", monster, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this monster', edit_monster_path(monster), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/monsters/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing monster</h1>

  <%= render "form", monster: @monster %>

  <%= link_to "Show this monster", @monster, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to monsters", monsters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/monsters/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Monsters</h1>
    <%= link_to 'New monster', new_monster_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="monsters" class="min-w-full">
    <%= render @monsters %>
  </div>
</div>

app/views/monsters/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New monster</h1>

  <%= render "form", monster: @monster %>

  <%= link_to 'Back to monsters', monsters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/monsters/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @monster %>

    <%= link_to 'Edit this monster', edit_monster_path(@monster), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this monster', monster_path(@monster), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to monsters', monsters_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>